source "https://rubygems.org"

gem "chef-acceptance", github: "chef/chef-acceptance"
gem "kitchen-ec2"
gem "inspec"
gem "kitchen-vagrant"
gem "windows_chef_zero"
gem "kitchen-inspec"
gem "test-kitchen"
gem "winrm-elevated"
gem "berkshelf"
gem "mixlib-install"

# nio4r 2.x was throwing a "could not install" error because of a Ruby version
# conflict (that didn't actually exist). Since the only gem that really needs
# it is celluloid, let's just pin it until it becomes a bigger problem.
gem "nio4r", ">= 1.1.0", "< 2.0.0"
